### ISSUE TITLE
How in the hecks do we actually github?

### ISSUE THREAD

**Issue by ace24713** [mohr24/sweetbeat#1]
Okay we need to figure this out, the current head doesn't open properly in GameMaker without the project file, and generating it from the included files changes a bunch of crap on things and everything ultimately breaks.

I'm sure some conflict on your end lead you to +ignore the project file, but we can't keep operating on back and forth ping-pong commit conflicts like this.

also I found this nifty issue tab so I'm experimenting with using it! :)

**Comment by ace24713** [comment]
@ravi4theja @mrmillers
If anyone has issues with conflicts we should bring it up in this thread.
I suspect this won't be very easy to get universally working.

**Comment by mohr24** [comment]
I agree it's going to be a problem. I realize that I shouldn't have
gitignored the project file. Not sure what we can do about it. I can even
just send you a zip for now.

**Comment by mohr24** [comment]
also took the project file off the gitignore list and added it back to the
head.
