### ISSUE TITLE
Dancing musical beats

### ISSUE THREAD

**Issue by ace24713** [mohr24/sweetbeat#10]
Make the music beats dance to the rhythm

this includes checkpoints and beats

I would recommend using this function draw_sprite_pos()
http://docs.yoyogames.com/source/dadiospice/002_reference/drawing/drawing%20sprites%20and%20backgrounds/draw_sprite_pos.html

you can skew and stretch the image programatically then.

Make it bounces more strongly when it is the active checkpoint

**Comment by mrmillers** [comment]
The sprite of the beat changed.
